# Generated by Django 5.2.7 on 2025-11-23 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_organization_address_organization_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "Organizers who can create, update, and cancel events "
                    "for this organization"
                ),
                related_name="collaborating_organizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
