# Generated by Django 5.2.7 on 2025-11-24 17:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_organization_email_alter_organization_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who follow this organization to track its events",
                related_name="followed_organizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
