# Generated by Django 5.2.7 on 2025-11-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
