# Generated by Django 5.2.7 on 2025-11-09 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="interested_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="interested_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="registered_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="registered_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
