# Generated by Django 5.2.7 on 2025-11-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_alter_event_participants"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["date", "id"]},
        ),
    ]
