# Generated by Django 5.2.7 on 2025-11-21 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_event_interested_users_event_organizer_and_more"),
        ("events", "0009_alter_event_options"),
    ]

    operations = []
