# Generated by Django 5.2.7 on 2025-11-21 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_organization_address_organization_city_and_more"),
        ("events", "0009_alter_event_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="accounts.organization",
            ),
        ),
    ]
