# Generated by Django 5.2.7 on 2025-11-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_remove_event_registered_users_alter_event_organizer"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("SOCIAL", "Social"),
                    ("ACADEMIC", "Academic"),
                    ("TRAVEL", "Travel"),
                    ("SPORTS", "Sports"),
                    ("CULTURAL", "Cultural"),
                    ("VOLUNTEERING", "Volunteering"),
                    ("NIGHTLIFE", "Nightlife"),
                ],
                default="SOCIAL",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
