# Generated by Django 5.2.7 on 2025-11-24 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_event_category"),
        ("events", "0012_merge_0011_migrations"),
    ]

    operations = []
