# Generated by Django 6.0 on 2025-12-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_merge_0012_event_category_0012_merge_0011_migrations"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="reminder_1h_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="reminder_24h_sent",
            field=models.BooleanField(default=False),
        ),
    ]
