var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/notifications/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__27ec23f8._.js")
R.c("server/chunks/ssr/_d25179f9._.js")
R.c("server/chunks/ssr/_a81bebe8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1257d2b0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__fefa2633._.js")
R.c("server/chunks/ssr/node_modules_next_dist_982e7503._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_e92fa76f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_notifications_page_actions_88bc8346.js")
R.m(21381)
module.exports=R.m(21381).exports
