var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/organizations/edit/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__324ec66d._.js")
R.c("server/chunks/ssr/_d25179f9._.js")
R.c("server/chunks/ssr/_83d48302._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1257d2b0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__fefa2633._.js")
R.c("server/chunks/ssr/node_modules_next_dist_982e7503._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_e92fa76f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_organizations_edit_page_actions_0b1a17bb.js")
R.m(49900)
module.exports=R.m(49900).exports
